### ISSUE TITLE
Improve transition between themes

### ISSUE THREAD

**Issue by nucliweb** [IBM/nicedoc.io#42]
We can improve the transition between themes.

## Current version

![Current version](https://user-images.githubusercontent.com/1307927/56279726-f33cee00-6108-11e9-9da9-eeac66aed801.gif)

## Version with transition

![Transotion version](https://user-images.githubusercontent.com/1307927/56279785-0ea7f900-6109-11e9-8cee-46ab8ec90327.gif)

**Comment by Kikobeats** [comment]
I really appreciated a PR of this 🙏
