### ISSUE TITLE
Doesn't handle `<br>` in Markdown

### ISSUE THREAD

**Issue by sindresorhus** [IBM/nicedoc.io#61]
I use `<br>` for hard linebreaks, but Nicedoc doesn't render them.

GitHub:

<img width="184" alt="Screen Shot 2019-04-18 at 21 41 13" src="https://user-images.githubusercontent.com/170270/56368997-b533ed00-6222-11e9-90af-c3a5c9af6254.png">

Nicedoc:

<img width="269" alt="Screen Shot 2019-04-18 at 21 40 57" src="https://user-images.githubusercontent.com/170270/56369009-b7964700-6222-11e9-9461-aa93ee5cfc87.png">

From: https://nicedoc.io/sindresorhus/got

**Comment by wooorm** [comment]
Must be related to https://github.com/IBM/nicedoc.io/pull/57 as well

**Comment by Kikobeats** [comment]
Yes, sorry for that, it was a little regression since we refactored the data pipeline
