### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by BenRoe** [IBM/nicedoc.io#85]
All images not loading.
https://nicedoc.io/hsgw/plaid/blob/master/doc/en/soldering.md

![nicedoc-img](https://user-images.githubusercontent.com/643834/58510034-307cad00-8198-11e9-9655-15a4681b65a7.png)

**Comment by Kikobeats** [comment]
It should be working now, can you confirm? 🙂

**Comment by BenRoe** [comment]
Great 👍 
What was the problem?

**Comment by BenRoe** [comment]
Found another repo where the images not loaded.
https://nicedoc.io/omkbd/ErgoDash/blob/master/Doc/build-en.md

**Comment by Kikobeats** [comment]
Thanks for reporting, it should be working properly right now 🙂
